"""created_at server default

Revision ID: 1ce97a6ee7b2
Revises: 5b70d72d27ef
Create Date: 2026-02-11 14:17:53.973579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce97a6ee7b2'
down_revision: Union[str, Sequence[str], None] = '5b70d72d27ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('users', 'created_at', server_default=sa.func.now())
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
