spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jwt_auth}
    username: ${SPRING_DATASOURCE_USERNAME:nikita}
    password: ${SPRING_DATASOURCE_PASSWORD:nikita}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  threads:
    virtual:
      enabled: true

jwt:
  secret: some-super-secret-key-that-is-long-enough-for-hmac
  expiration: 900000

resend:
  api:
    key: re_3KzzZD47_BxhPwFXFNzRqpqxT1vvPTVzJ

Ai:
  AI_API_KEY: "pza_g9Xz2YHx_ETB8QEBlamkSP3FsExa2Ea5"
  AI_MODEL: "deepseek/deepseek-chat-v3-0324"
  AI_TIMEOUT_MS: 30000
  AiUrl: "https://polza.ai/api/v1/chat/completions"






