spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jwt_auth}
    username: ${SPRING_DATASOURCE_USERNAME:nikita}
    password: ${SPRING_DATASOURCE_PASSWORD:nikita}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
  threads:
    virtual:
      enabled: true

jwt:
  secret: some-super-secret-key-that-is-long-enough-for-hmac
  expiration: 86400000

resend:
  api:
    key: re_3KzzZD47_BxhPwFXFNzRqpqxT1vvPTVzJ





