CREATE TABLE IF NOT EXISTS users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255)                            NOT NULL,
    hashed_password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uc_users_username'
    ) THEN
        ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);
    END IF;
END $$;