-- Заменяем отдельные sequence на IDENTITY (как в таблице users)

DROP SEQUENCE IF EXISTS confirmation_codes_seq CASCADE;
ALTER TABLE confirmation_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

DROP SEQUENCE IF EXISTS refresh_tokens_seq CASCADE;
ALTER TABLE refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;